name: Deploy Lambd S3 API Gateway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy the Serverless Lambda function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: action/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: yarn install

    - name: Deploy the Serverless function
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
